apiVersion: apps/v1
kind: Deployment
metadata:
  name: decisiontreeclassifier-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decisiontreeclassifier-app
  template:
    metadata:
      labels:
        app: decisiontreeclassifier-app
    spec:
      containers:
        - name: decisiontreeclassifier-container
          image: <docker-image>:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: decisiontreeclassifier-service
spec:
  selector:
    app: decisiontreeclassifier-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
